// Generated by scripts/sync-course-notes.ts from main.toc and main.pdf. Do not edit by hand.
import type { NotesChapter } from "../_site/courseModel";

export const notesPageOffset = 2;

export const notesChapters: readonly NotesChapter[] = [
  {
    number: 1,
    title: "מרחבי מכפלה פנימית",
    page: 1,
    sections: [
      { number: "1.1", title: "מרחק, נורמה ומכפלה פנימית", page: 1 },
      { number: "1.2", title: "מרחבי מכפלה פנימית", page: 6 },
      { number: "1.3", title: "התכנסויות במרחבים נורמיים", page: 16 },
    ],
  },
  {
    number: 2,
    title: "טורי פוריה",
    page: 27,
    sections: [
      { number: "2.1", title: "התכנסות נקודתית ובמידה שווה", page: 32 },
      { number: "2.2", title: "טורי סינוסים וקוסינוסים", page: 38 },
      { number: "2.3", title: "טורי פוריה בקטע כללי", page: 42 },
      { number: "2.4", title: "שימושים במד״ר ומד״ח", page: 45 },
      { number: "2.5", title: "נספח – הוכחת משפט דיריכלה", page: 50 },
    ],
  },
  {
    number: 3,
    title: "התמרת פוריה",
    page: 55,
    sections: [
      { number: "3.1", title: "מבוא והגדרות", page: 55 },
      { number: "3.2", title: "תכונות התמרת פוריה עבור פונקציות רציפות למקוטעין ואינטגרביליות בהחלט", page: 58 },
      { number: "3.3", title: "נוסחאות היפוך והתמרת פוריה עבור פונקציות רציפות למקוטעין וריבוע־אינטגרביליות", page: 66 },
      { number: "3.4", title: "קונבולוציה של פונקציות רציפות למקוטעין ואינטגרביליות בהחלט", page: 74 },
      { number: "3.5", title: "שימושים למד״ח", page: 82 },
    ],
  },
  {
    number: 4,
    title: "התמרת לפלס",
    page: 84,
    sections: [
      { number: "4.1", title: "מבוא והגדרות", page: 84 },
      { number: "4.2", title: "תכונות של התמרת לפלס", page: 86 },
      { number: "4.3", title: "פונקציית הביסייד ופונקציית דלתא של דיראק", page: 91 },
      { number: "4.4", title: "קונבולוציה", page: 101 },
      { number: "4.5", title: "ההתמרה ההפוכה", page: 105 },
    ],
  },
];
