// Generated by scripts/sync-course-notes.ts from main.toc and main.pdf. Do not edit by hand.
import type { NotesChapter } from "../_site/courseModel";

export const notesPageOffset = 4;

export const notesChapters: readonly NotesChapter[] = [
  {
    number: 1,
    title: "סדרות וטורים של פונקציות",
    page: 1,
    sections: [
      { number: "1.1", title: "סדרות של פונקציות", page: 1 },
      { number: "1.2", title: "טורים של פונקציות", page: 16 },
      { number: "1.3", title: "טורי חזקות", page: 28 },
      { number: "1.4", title: "נספח – גבולות חלקיים", page: 41 },
      { number: "1.5", title: "נספח – חישובי גבולות", page: 43 },
    ],
  },
  {
    number: 2,
    title: "מבוא למד״ר ומשוואות מסדר ראשון",
    page: 46,
    sections: [
      { number: "2.1", title: "מבוא והגדרות", page: 47 },
      { number: "2.2", title: "משוואות ליניאריות", page: 50 },
      { number: "2.3", title: "עקרון ההדבקה", page: 52 },
      { number: "2.4", title: "משוואות פרידות", page: 53 },
      { number: "2.5", title: "משוואה מטיפוס הומוגני", page: 55 },
      { number: "2.6", title: "החלפת תפקידי המשתנים", page: 58 },
      { number: "2.7", title: "משוואות מדויקות", page: 59 },
    ],
  },
  {
    number: 3,
    title: "התורה האיכותית של מד״ר",
    page: 67,
    sections: [
      { number: "3.1", title: "משפחות של עקומים ומשפחות אורתוגונליות", page: 67 },
      { number: "3.2", title: "שדה הכיוונים", page: 72 },
      { number: "3.3", title: "קיום ו/או יחידות של פתרון לבעיית התחלה", page: 77 },
      { number: "3.4", title: "יציבות של פתרונות", page: 85 },
      { number: "3.5", title: "נספח (להשערה בלבד) – הוכחת משפט הקיום והיחידות", page: 91 },
    ],
  },
  {
    number: 4,
    title: "משוואות מסדר גבוה",
    page: 97,
    sections: [
      { number: "4.1", title: "מבוא, קיום ויחידות", page: 97 },
      { number: "4.2", title: "משוואות ליניאריות מסדר גבוה", page: 100 },
      { number: "4.3", title: "מרחב הפתרונות למשוואה ליניארית", page: 101 },
      { number: "4.4", title: "משוואות ליניאריות במקדמים קבועים", page: 116 },
      { number: "4.5", title: "יציבות במשוואות מסדר גבוה", page: 124 },
      { number: "4.6", title: "משוואות אוילר", page: 128 },
      { number: "4.7", title: "המשוואה האי־הומוגנית", page: 131 },
      { number: "4.8", title: "פתרון על ידי טורי חזקות", page: 143 },
      { number: "4.9", title: "נספח – אלגברה ליניארית", page: 148 },
    ],
  },
  {
    number: 5,
    title: "מערכות מד״ר",
    page: 157,
    sections: [
      { number: "5.1", title: "מערכת מד״ר ליניארית הומוגנית", page: 158 },
      { number: "5.2", title: "מערכת משוואות במקדמים קבועים", page: 162 },
      { number: "5.3", title: "מישור הפאזה", page: 175 },
      { number: "5.4", title: "נספח – לכסון מטריצות וצורת ז׳ורדן", page: 188 },
    ],
  },
  {
    number: 6,
    title: "תורת שטורם ליוביל",
    page: 193,
    sections: [
      { number: "6.1", title: "היסטוריה ומוטיבציה", page: 193 },
      { number: "6.2", title: "אופרטורי שטורם־ליוביל", page: 198 },
      { number: "6.3", title: "הערכים העצמיים של בעית שטורם ליוביל", page: 199 },
      { number: "6.4", title: "פיתוח לטור בפונקציות עצמיות", page: 208 },
      { number: "6.5", title: "פתרון בעיות שפה אי־הומוגנית", page: 212 },
    ],
  },
];
